In [1]:
import numpy as np

In [3]:
data = np.genfromtxt("ccpp_train.csv",delimiter = ",")

In [4]:
type(data)

numpy.ndarray

In [5]:
data.shape

(7176, 5)

In [6]:
X = data[:,:-1]
Y = data[:,-1].reshape(-1,1)

In [7]:
X.shape

(7176, 4)

In [8]:
Y.shape

(7176, 1)

In [9]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [11]:
X = scaler.transform(X)


In [51]:
X.shape

(7176, 4)

In [52]:
v = np.ones((len(data),1))
X = np.append(X,v,axis=1)

In [53]:
X.shape

(7176, 5)

In [54]:
M = len(data)
n = X.shape[1]

## writing gradient descent algo

In [55]:
def step_gradient(m,learning_rate,X,Y):
    m_slope = np.zeros(n)
    for i in range(M):
        x = X[i,:]
        y = Y[i]
        for j in range(n):
            m_slope[j] += (-2/M)*((y - np.sum(m*x))*x[j])
    m = m - learning_rate*m_slope
    return m

In [56]:
def cost(x,y,m):
    total_cost = 0
    for i in range(M):
        x = X[i,:]
        y = Y[i]
        total_cost += ((1/M)*(((y-np.sum(m*x)))**2))
    return total_cost

In [57]:
def gd(learning_rate,num_iterations,x,y):
    m = np.zeros(n)
    for i in range(num_iterations):
        m = step_gradient(m,learning_rate,x,y)
        print(i, "the cost is",cost(x,y,m))
    return m 

In [58]:
def run():
    M = len(data)
    n = X.shape[1]
    learning_rate = .4
    num_iterations = 200
    x = X
    y = Y
    m = gd(learning_rate,num_iterations,x,y)
    return m

In [34]:
#run()

0 the cost is [206766.93958422]
1 the cost is [206743.04844685]
2 the cost is [206723.27380463]
3 the cost is [206705.87351333]
4 the cost is [206690.22244688]
5 the cost is [206676.03195177]
6 the cost is [206663.12707822]
7 the cost is [206651.37688699]
8 the cost is [206640.67163897]
9 the cost is [206630.91482353]
10 the cost is [206622.01996911]
11 the cost is [206613.90904369]
12 the cost is [206606.51142371]
13 the cost is [206599.76309961]
14 the cost is [206593.60600636]
15 the cost is [206587.98743739]
16 the cost is [206582.85952403]
17 the cost is [206578.17877011]
18 the cost is [206573.90563476]
19 the cost is [206570.00415769]
20 the cost is [206566.44162221]
21 the cost is [206563.18825186]
22 the cost is [206560.21693703]
23 the cost is [206557.50298836]
24 the cost is [206555.02391408]
25 the cost is [206552.75921883]
26 the cost is [206550.69022174]
27 the cost is [206548.79989182]
28 the cost is [206547.07269883]
29 the cost is [206545.49447819]
30 the cost is [2065

array([-14.90193452,  -2.89355451,   0.34921642,  -2.34279618])

In [59]:
k = run()

0 the cost is [8519.45135476]
1 the cost is [565.66068821]
2 the cost is [228.69006483]
3 the cost is [198.60193427]
4 the cost is [182.44335426]
5 the cost is [168.23255861]
6 the cost is [155.32687303]
7 the cost is [143.57664932]
8 the cost is [132.87140001]
9 the cost is [123.11458451]
10 the cost is [114.21973009]
11 the cost is [106.10880467]
12 the cost is [98.71118469]
13 the cost is [91.96286059]
14 the cost is [85.80576734]
15 the cost is [80.18719837]
16 the cost is [75.05928501]
17 the cost is [70.37853109]
18 the cost is [66.10539575]
19 the cost is [62.20391867]
20 the cost is [58.64138319]
21 the cost is [55.38801284]
22 the cost is [52.41669801]
23 the cost is [49.70274934]
24 the cost is [47.22367506]
25 the cost is [44.95897981]
26 the cost is [42.88998272]
27 the cost is [40.9996528]
28 the cost is [39.27245981]
29 the cost is [37.69423917]
30 the cost is [36.25206946]
31 the cost is [34.93416123]
32 the cost is [33.72975617]
33 the cost is [32.62903536]
34 the cost 

In [60]:
k.shape

(5,)

In [61]:
k = k.reshape(-1,1)

## calculationg Y_pred for training

In [62]:
def pred_train(X,k):
    y = np.dot(X,k)
    
   
    return y

In [63]:
Y_pred_train = pred_train(X,k)

In [64]:
def score(Y,Y_pred_train,): 
    u  = ((Y_pred_train - Y)**2).sum()
    v =  ((Y_pred_train - Y.mean())**2).sum()
    return (1 - u/v)

In [65]:
print(score(Y,Y_pred_train))

0.9232814375424967


## y_pred for testing

In [66]:
X_test = np.loadtxt("ccpp_test.csv",delimiter = ",")


In [67]:
X_test.shape

(2392, 4)

In [68]:
X_test= scaler.transform(X_test)

In [69]:
v = np.ones((len(X_test),1))
X_test = np.append(X_test,v,axis=1)

In [70]:
X_test.shape
X_test

array([[-1.02742256, -0.96138014,  0.72378329,  1.20446479,  1.        ],
       [-1.01136848, -1.25783726, -0.09942787,  0.57331371,  1.        ],
       [ 0.97398614,  1.62360048, -1.27807846,  0.39005424,  1.        ],
       ...,
       [ 0.62748557,  0.93814142, -0.69965107,  1.27284519,  1.        ],
       [ 0.51644485, -0.90099073,  0.11685368, -0.54470581,  1.        ],
       [ 0.28499852,  0.46914312,  0.95515424,  0.80580707,  1.        ]])

In [71]:
def pred_test(X_test,k):
    y = np.dot(X_test,k)
    
   
    return y

In [72]:
Y_pred_test = pred_test(X_test,k)


In [73]:
np.savetxt("ccpp_predicted_test_afterscaling1.csv",Y_pred_test,delimiter=',')